name: Check Service Status

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Services
        run: |
          rm -rf status
          mkdir -p status
          TIMESTAMP=$(date -Iseconds)

          jq -c '.[]' services.json | while read service; do
            ID=$(echo "$service" | jq -r '.id')
            URL=$(echo "$service" | jq -r '.url')

            STATUS="down"
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 10 "$URL")

            if [ "$HTTP_CODE" -eq 200 ]; then
              STATUS="up"
            fi

            FILE="status/status-$ID.json"

            echo "[" > "$FILE"
            echo "  {\"timestamp\": \"$TIMESTAMP\", \"status\": \"$STATUS\"}" >> "$FILE"
            echo "]" >> "$FILE"
          done

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add status/
          git commit -m "fix: improve status check logic and clear invalid results" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
